<?php

declare(strict_types=1);

return [
    'login' => ['controller' => 'AuthController', 'method' => 'showLogin', 'public' => true, 'methods' => ['GET']],
    'login-submit' => ['controller' => 'AuthController', 'method' => 'login', 'public' => true, 'methods' => ['POST']],
    'register' => ['controller' => 'AuthController', 'method' => 'showRegister', 'public' => true, 'methods' => ['GET']],
    'register-submit' => ['controller' => 'AuthController', 'method' => 'register', 'public' => true, 'methods' => ['POST']],
    'forgot-password' => ['controller' => 'AuthController', 'method' => 'showForgotPassword', 'public' => true, 'methods' => ['GET']],
    'forgot-password-submit' => ['controller' => 'AuthController', 'method' => 'forgotPassword', 'public' => true, 'methods' => ['POST']],
    'reset-password' => ['controller' => 'AuthController', 'method' => 'showResetPassword', 'public' => true, 'methods' => ['GET']],
    'reset-password-submit' => ['controller' => 'AuthController', 'method' => 'resetPassword', 'public' => true, 'methods' => ['POST']],
    'logout' => ['controller' => 'AuthController', 'method' => 'logout', 'methods' => ['POST']],
    'auth-switch-role' => ['controller' => 'AuthController', 'method' => 'switchRole', 'roles' => ['admin', 'kepala_lppm', 'dosen'], 'methods' => ['POST']],
    'auth-impersonate' => ['controller' => 'AuthController', 'method' => 'impersonate', 'roles' => ['admin', 'kepala_lppm'], 'methods' => ['POST']],
    'auth-impersonate-exit' => ['controller' => 'AuthController', 'method' => 'stopImpersonate', 'roles' => ['admin', 'kepala_lppm', 'dosen'], 'methods' => ['POST']],

    'dashboard' => ['controller' => 'DashboardController', 'method' => 'index'],
    'dashboard-admin' => ['controller' => 'DashboardController', 'method' => 'admin', 'roles' => ['admin', 'kepala_lppm']],
    'dashboard-dosen' => ['controller' => 'DashboardController', 'method' => 'dosen', 'roles' => ['dosen']],

    'letters' => ['controller' => 'LetterController', 'method' => 'index', 'roles' => ['admin', 'kepala_lppm', 'dosen']],
    'letters-store' => ['controller' => 'LetterController', 'method' => 'store', 'roles' => ['admin', 'kepala_lppm', 'dosen'], 'methods' => ['POST']],
    'letters-show' => ['controller' => 'LetterController', 'method' => 'show', 'roles' => ['admin', 'kepala_lppm', 'dosen']],
    'my-letters' => ['controller' => 'LetterController', 'method' => 'myLetters', 'roles' => ['dosen']],
    'my-letters-detail' => ['controller' => 'LetterController', 'method' => 'myLetterDetail', 'roles' => ['dosen']],
    'ajukan-surat' => ['controller' => 'LetterController', 'method' => 'submissionMenu', 'roles' => ['dosen']],
    'surat-kontrak-submit' => ['controller' => 'LetterController', 'method' => 'submitContract', 'roles' => ['dosen'], 'methods' => ['POST']],
    'letters-approve' => ['controller' => 'LetterController', 'method' => 'approve', 'roles' => ['kepala_lppm'], 'methods' => ['POST']],
    'letters-reject' => ['controller' => 'LetterController', 'method' => 'reject', 'roles' => ['kepala_lppm'], 'methods' => ['POST']],
    'letters-head-direct-update' => ['controller' => 'LetterController', 'method' => 'headDirectUpdate', 'roles' => ['kepala_lppm'], 'methods' => ['POST']],
    'letters-preview' => ['controller' => 'LetterPdfController', 'method' => 'preview', 'roles' => ['admin', 'kepala_lppm', 'dosen']],
    'letters-generate-pdf' => ['controller' => 'LetterPdfController', 'method' => 'generate', 'roles' => ['kepala_lppm'], 'methods' => ['POST']],
    'letters-download-pdf' => ['controller' => 'LetterPdfController', 'method' => 'download', 'roles' => ['admin', 'kepala_lppm', 'dosen']],
    'letters-attachment' => ['controller' => 'ProtectedFileController', 'method' => 'letterAttachment', 'roles' => ['admin', 'kepala_lppm', 'dosen']],
    'status-luaran-file' => ['controller' => 'ProtectedFileController', 'method' => 'outputEvidence', 'roles' => ['dosen']],

    'verify' => ['controller' => 'VerifyController', 'method' => 'show', 'public' => true],

    'contracts' => ['controller' => 'ContractController', 'method' => 'index', 'roles' => ['admin']],
    'settings-letter-number' => ['controller' => 'SettingController', 'method' => 'letterNumber', 'roles' => ['admin', 'kepala_lppm']],
    'settings-letter-number-save' => ['controller' => 'SettingController', 'method' => 'letterNumber', 'roles' => ['admin', 'kepala_lppm']],
    'settings-contract' => ['controller' => 'SettingController', 'method' => 'contract', 'roles' => ['admin', 'kepala_lppm']],
    'settings-contract-detail' => ['controller' => 'SettingController', 'method' => 'contractDetail', 'roles' => ['admin', 'kepala_lppm']],
    'settings-contract-save' => ['controller' => 'SettingController', 'method' => 'contract', 'roles' => ['admin', 'kepala_lppm']],
    'settings-contract-delete' => ['controller' => 'SettingController', 'method' => 'deleteContractYear', 'roles' => ['admin', 'kepala_lppm']],
    'archives' => ['controller' => 'ArchiveController', 'method' => 'index', 'roles' => ['kepala_lppm']],
    'archives-delete' => ['controller' => 'ArchiveController', 'method' => 'delete', 'roles' => ['kepala_lppm'], 'methods' => ['POST']],
    'users' => ['controller' => 'UserController', 'method' => 'index', 'roles' => ['admin', 'kepala_lppm']],
    'users-dosen-show' => ['controller' => 'UserController', 'method' => 'showDosen', 'roles' => ['admin', 'kepala_lppm']],
    'users-dosen-edit' => ['controller' => 'UserController', 'method' => 'editDosen', 'roles' => ['admin', 'kepala_lppm']],
    'users-dosen-update' => ['controller' => 'UserController', 'method' => 'updateDosen', 'roles' => ['admin', 'kepala_lppm'], 'methods' => ['POST']],
    'users-dosen-delete' => ['controller' => 'UserController', 'method' => 'deleteDosen', 'roles' => ['admin', 'kepala_lppm'], 'methods' => ['POST']],
    'users-dosen-bulk-delete' => ['controller' => 'UserController', 'method' => 'bulkDeleteDosen', 'roles' => ['admin'], 'methods' => ['POST']],
    'users-change-role' => ['controller' => 'UserController', 'method' => 'changeRole', 'roles' => ['admin'], 'methods' => ['POST']],
    'users-profile' => ['controller' => 'UserController', 'method' => 'profile', 'roles' => ['admin', 'kepala_lppm']],
    'users-upload-signature' => ['controller' => 'UserController', 'method' => 'uploadSignature', 'roles' => ['admin', 'kepala_lppm'], 'methods' => ['POST']],
    'users-avatar' => ['controller' => 'ProtectedFileController', 'method' => 'userAvatar', 'roles' => ['admin', 'kepala_lppm', 'dosen']],
    'profile' => ['controller' => 'UserController', 'method' => 'myProfile', 'roles' => ['dosen']],
    'profile-update' => ['controller' => 'UserController', 'method' => 'updateMyProfile', 'roles' => ['dosen'], 'methods' => ['POST']],
    'status-luaran' => ['controller' => 'StatusLuaranController', 'method' => 'index', 'roles' => ['dosen']],
    'status-luaran-detail' => ['controller' => 'StatusLuaranController', 'method' => 'detail', 'roles' => ['dosen']],
    'status-luaran-save' => ['controller' => 'StatusLuaranController', 'method' => 'save', 'roles' => ['dosen'], 'methods' => ['POST']],

    'data-penelitian' => ['controller' => 'DataPenelitianController', 'method' => 'index', 'roles' => ['dosen']],
    'data-penelitian-create' => ['controller' => 'DataPenelitianController', 'method' => 'create', 'roles' => ['dosen']],
    'data-penelitian-store' => ['controller' => 'DataPenelitianController', 'method' => 'store', 'roles' => ['dosen'], 'methods' => ['POST']],
    'data-penelitian-update' => ['controller' => 'DataPenelitianController', 'method' => 'update', 'roles' => ['dosen'], 'methods' => ['POST']],
    'data-penelitian-show' => ['controller' => 'DataPenelitianController', 'method' => 'show', 'roles' => ['dosen']],
    'data-penelitian-edit' => ['controller' => 'DataPenelitianController', 'method' => 'edit', 'roles' => ['dosen']],
    'data-penelitian-delete' => ['controller' => 'DataPenelitianController', 'method' => 'destroy', 'roles' => ['dosen'], 'methods' => ['POST']],

    'data-pengabdian' => ['controller' => 'DataPengabdianController', 'method' => 'index', 'roles' => ['dosen']],
    'data-pengabdian-create' => ['controller' => 'DataPengabdianController', 'method' => 'create', 'roles' => ['dosen']],
    'data-pengabdian-store' => ['controller' => 'DataPengabdianController', 'method' => 'store', 'roles' => ['dosen'], 'methods' => ['POST']],
    'data-pengabdian-update' => ['controller' => 'DataPengabdianController', 'method' => 'update', 'roles' => ['dosen'], 'methods' => ['POST']],
    'data-pengabdian-show' => ['controller' => 'DataPengabdianController', 'method' => 'show', 'roles' => ['dosen']],
    'data-pengabdian-edit' => ['controller' => 'DataPengabdianController', 'method' => 'edit', 'roles' => ['dosen']],
    'data-pengabdian-delete' => ['controller' => 'DataPengabdianController', 'method' => 'destroy', 'roles' => ['dosen'], 'methods' => ['POST']],

    'data-hilirisasi' => ['controller' => 'DataHilirisasiController', 'method' => 'index', 'roles' => ['dosen']],
    'data-hilirisasi-create' => ['controller' => 'DataHilirisasiController', 'method' => 'create', 'roles' => ['dosen']],
    'data-hilirisasi-store' => ['controller' => 'DataHilirisasiController', 'method' => 'store', 'roles' => ['dosen'], 'methods' => ['POST']],
    'data-hilirisasi-update' => ['controller' => 'DataHilirisasiController', 'method' => 'update', 'roles' => ['dosen'], 'methods' => ['POST']],
    'data-hilirisasi-show' => ['controller' => 'DataHilirisasiController', 'method' => 'show', 'roles' => ['dosen']],
    'data-hilirisasi-edit' => ['controller' => 'DataHilirisasiController', 'method' => 'edit', 'roles' => ['dosen']],
    'data-hilirisasi-delete' => ['controller' => 'DataHilirisasiController', 'method' => 'destroy', 'roles' => ['dosen'], 'methods' => ['POST']],

    'surat-penelitian-kontrak' => ['controller' => 'LetterController', 'method' => 'create', 'roles' => ['dosen']],
    'surat-penelitian-izin' => ['controller' => 'LetterController', 'method' => 'create', 'roles' => ['dosen']],
    'surat-penelitian-tugas' => ['controller' => 'LetterController', 'method' => 'create', 'roles' => ['dosen']],
    'surat-pengabdian-kontrak' => ['controller' => 'LetterController', 'method' => 'create', 'roles' => ['dosen']],
    'surat-pengabdian-izin' => ['controller' => 'LetterController', 'method' => 'create', 'roles' => ['dosen']],
    'surat-pengabdian-tugas' => ['controller' => 'LetterController', 'method' => 'create', 'roles' => ['dosen']],
    'surat-hilirisasi-kontrak' => ['controller' => 'LetterController', 'method' => 'create', 'roles' => ['dosen']],
    'surat-hilirisasi-izin' => ['controller' => 'LetterController', 'method' => 'create', 'roles' => ['dosen']],
    'surat-hilirisasi-tugas' => ['controller' => 'LetterController', 'method' => 'create', 'roles' => ['dosen']],

    'logs' => ['controller' => 'ActivityLogController', 'method' => 'index', 'roles' => ['admin', 'kepala_lppm']],
    'logs-bulk-delete' => ['controller' => 'ActivityLogController', 'method' => 'bulkDelete', 'roles' => ['admin', 'kepala_lppm'], 'methods' => ['POST']],
    'master-data-outputs' => ['controller' => 'MasterDataController', 'method' => 'outputs', 'roles' => ['admin']],
    'master-data-outputs-create' => ['controller' => 'MasterDataController', 'method' => 'createOutput', 'roles' => ['admin']],
    'master-data-outputs-edit' => ['controller' => 'MasterDataController', 'method' => 'editOutput', 'roles' => ['admin']],
    'master-data-outputs-save' => ['controller' => 'MasterDataController', 'method' => 'saveOutput', 'roles' => ['admin'], 'methods' => ['POST']],
    'master-data-outputs-delete' => ['controller' => 'MasterDataController', 'method' => 'deleteOutput', 'roles' => ['admin'], 'methods' => ['POST']],
    'master-data-schemes' => ['controller' => 'MasterDataController', 'method' => 'schemes', 'roles' => ['admin']],
    'master-data-schemes-create' => ['controller' => 'MasterDataController', 'method' => 'createScheme', 'roles' => ['admin']],
    'master-data-schemes-edit' => ['controller' => 'MasterDataController', 'method' => 'editScheme', 'roles' => ['admin']],
    'master-data-schemes-save' => ['controller' => 'MasterDataController', 'method' => 'saveScheme', 'roles' => ['admin'], 'methods' => ['POST']],
    'master-data-schemes-delete' => ['controller' => 'MasterDataController', 'method' => 'deleteScheme', 'roles' => ['admin'], 'methods' => ['POST']],
    'master-data-scopes' => ['controller' => 'MasterDataController', 'method' => 'scopes', 'roles' => ['admin']],
    'master-data-scopes-create' => ['controller' => 'MasterDataController', 'method' => 'createScope', 'roles' => ['admin']],
    'master-data-scopes-edit' => ['controller' => 'MasterDataController', 'method' => 'editScope', 'roles' => ['admin']],
    'master-data-scopes-save' => ['controller' => 'MasterDataController', 'method' => 'saveScope', 'roles' => ['admin'], 'methods' => ['POST']],
    'master-data-scopes-delete' => ['controller' => 'MasterDataController', 'method' => 'deleteScope', 'roles' => ['admin'], 'methods' => ['POST']],
    'master-data-funding-sources' => ['controller' => 'MasterDataController', 'method' => 'fundingSources', 'roles' => ['admin']],
    'master-data-funding-sources-create' => ['controller' => 'MasterDataController', 'method' => 'createFundingSource', 'roles' => ['admin']],
    'master-data-funding-sources-edit' => ['controller' => 'MasterDataController', 'method' => 'editFundingSource', 'roles' => ['admin']],
    'master-data-funding-sources-save' => ['controller' => 'MasterDataController', 'method' => 'saveFundingSource', 'roles' => ['admin'], 'methods' => ['POST']],
    'master-data-funding-sources-delete' => ['controller' => 'MasterDataController', 'method' => 'deleteFundingSource', 'roles' => ['admin'], 'methods' => ['POST']],
];
