CREATE TABLE IF NOT EXISTS data_penelitian (
    id INT AUTO_INCREMENT PRIMARY KEY,
    kode_kegiatan VARCHAR(40) NOT NULL,
    judul VARCHAR(255) NOT NULL,
    skema VARCHAR(150) NOT NULL,
    ruang_lingkup VARCHAR(200) NOT NULL DEFAULT '',
    sumber_dana VARCHAR(150) NOT NULL,
    tahun VARCHAR(4) NOT NULL,
    ketua VARCHAR(150) NOT NULL,
    anggota TEXT NOT NULL,
    lokasi VARCHAR(255) NOT NULL,
    mitra VARCHAR(255) NOT NULL,
    total_dana_disetujui VARCHAR(100) NOT NULL DEFAULT '',
    tanggal_mulai DATE NOT NULL,
    tanggal_selesai DATE NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'draft',
    deskripsi TEXT NOT NULL,
    created_by INT NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    INDEX idx_dp_created_by (created_by),
    INDEX idx_dp_tahun (tahun),
    INDEX idx_dp_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS data_pengabdian (
    id INT AUTO_INCREMENT PRIMARY KEY,
    kode_kegiatan VARCHAR(40) NOT NULL,
    judul VARCHAR(255) NOT NULL,
    skema VARCHAR(150) NOT NULL,
    ruang_lingkup VARCHAR(200) NOT NULL DEFAULT '',
    sumber_dana VARCHAR(150) NOT NULL,
    tahun VARCHAR(4) NOT NULL,
    ketua VARCHAR(150) NOT NULL,
    anggota TEXT NOT NULL,
    lokasi VARCHAR(255) NOT NULL,
    mitra VARCHAR(255) NOT NULL,
    total_dana_disetujui VARCHAR(100) NOT NULL DEFAULT '',
    tanggal_mulai DATE NOT NULL,
    tanggal_selesai DATE NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'draft',
    deskripsi TEXT NOT NULL,
    created_by INT NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    INDEX idx_dpg_created_by (created_by),
    INDEX idx_dpg_tahun (tahun),
    INDEX idx_dpg_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS data_hilirisasi (
    id INT AUTO_INCREMENT PRIMARY KEY,
    kode_kegiatan VARCHAR(40) NOT NULL,
    judul VARCHAR(255) NOT NULL,
    skema VARCHAR(150) NOT NULL,
    ruang_lingkup VARCHAR(200) NOT NULL DEFAULT '',
    sumber_dana VARCHAR(150) NOT NULL,
    tahun VARCHAR(4) NOT NULL,
    ketua VARCHAR(150) NOT NULL,
    anggota TEXT NOT NULL,
    lokasi VARCHAR(255) NOT NULL,
    mitra VARCHAR(255) NOT NULL,
    total_dana_disetujui VARCHAR(100) NOT NULL DEFAULT '',
    tanggal_mulai DATE NOT NULL,
    tanggal_selesai DATE NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'draft',
    deskripsi TEXT NOT NULL,
    created_by INT NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    INDEX idx_dpr_created_by (created_by),
    INDEX idx_dpr_tahun (tahun),
    INDEX idx_dpr_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
